export const APP_CONFIG = {
    NAME: 'Test'
};

export const API_CONFIG: {
    PROTOCOL: string;
    ENDPOINT: string;
    PORT: string;
    ENDPOINT_WITH_PORT: string;
    ENDPOINT_WITH_PROTOCOL_AND_PORT: string;
    FULL_ENDPOINT: string;
    SOCKET_PORT: string;
    SOCKET_URL: string;
} = {
    PROTOCOL: 'http',
    ENDPOINT: '127.0.0.1',
    PORT: ':3000',
    ENDPOINT_WITH_PORT: '',
    ENDPOINT_WITH_PROTOCOL_AND_PORT: '',
    FULL_ENDPOINT: '',
    SOCKET_PORT: ':5000',
    SOCKET_URL: ''
};
API_CONFIG.ENDPOINT_WITH_PORT = API_CONFIG.ENDPOINT + API_CONFIG.PORT;
API_CONFIG.ENDPOINT_WITH_PROTOCOL_AND_PORT = API_CONFIG.PROTOCOL + '://' + API_CONFIG.ENDPOINT_WITH_PORT;
API_CONFIG.FULL_ENDPOINT = API_CONFIG.ENDPOINT_WITH_PROTOCOL_AND_PORT + '/';
API_CONFIG.SOCKET_URL = API_CONFIG.PROTOCOL + '://' +API_CONFIG.ENDPOINT + API_CONFIG.SOCKET_PORT;

